import type { Command } from 'commander';

import { type CompletionShell, renderCompletion, SUPPORTED_SHELLS } from '../lib/completion';
import { CliError, EXIT } from '../lib/http';

/**
 * `crowi completion <bash|zsh|fish>` — print a shell-completion script to
 * stdout. The script is generated by introspecting the live command tree, so
 * it stays in sync with the registered commands and flags automatically.
 *
 * Usage hints (printed by `--help`):
 *   bash: eval "$(crowi completion bash)"  (or save under a completions dir)
 *   zsh:  crowi completion zsh > "${fpath[1]}/_crowi"
 *   fish: crowi completion fish > ~/.config/fish/completions/crowi.fish
 */
export function registerCompletion(program: Command): void {
  program
    .command('completion <shell>')
    .description(`Print a shell-completion script (${SUPPORTED_SHELLS.join(' | ')})`)
    .addHelpText(
      'after',
      [
        '',
        'Examples:',
        '  bash:  eval "$(crowi completion bash)"',
        '  zsh:   crowi completion zsh > "${fpath[1]}/_crowi"',
        '  fish:  crowi completion fish > ~/.config/fish/completions/crowi.fish',
      ].join('\n'),
    )
    .action((shell: string) => {
      if (!SUPPORTED_SHELLS.includes(shell as CompletionShell)) {
        throw new CliError(`unsupported shell "${shell}" — choose one of: ${SUPPORTED_SHELLS.join(', ')}`, {
          exitCode: EXIT.INVALID,
        });
      }
      // Introspect the root program (not the `completion` subcommand) so the
      // emitted script covers every registered command + global flag.
      const root = program;
      process.stdout.write(renderCompletion(root, shell as CompletionShell));
    });
}
