#!/usr/bin/env node
// Regenerates the two hand-generated, gitignored design-sync build inputs.
// Run before the converter (this is cfg.buildCmd). Idempotent.
//   packages/web/.ds-entry.mjs   — re-exports ONLY the scoped shadcn primitives
//                                  (keeps the app's @paraglide i18n glue out of
//                                  the standalone bundle)
//   packages/web/.ds-compiled.css — Tailwind v4 compile of globals.css
//                                  (utilities + :root/.dark token values)
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cfg = JSON.parse(readFileSync(join(repoRoot, '.design-sync/config.json'), 'utf8'));
const webDir = join(repoRoot, 'packages/web');

// 1. entry — export * for each componentSrcMap src path (packages/web-relative)
const paths = [...new Set(Object.values(cfg.componentSrcMap).filter((v) => typeof v === 'string'))].sort();
const entry = [
  '// Design-sync bundle entry — regenerated by .design-sync/prepare.mjs. Do not hand-edit.',
  '// Re-exports ONLY the scoped shadcn primitives (keeps app i18n glue out of the bundle).',
  ...paths.map((p) => `export * from ${JSON.stringify('./' + p)};`),
  '',
].join('\n');
writeFileSync(join(webDir, '.ds-entry.mjs'), entry);

// 2. CSS — Tailwind v4 compile of globals.css
const tw = join(repoRoot, '.ds-sync/node_modules/.bin/tailwindcss');
execFileSync(tw, ['-i', 'src/app/globals.css', '-o', '.ds-compiled.css'], { cwd: webDir, stdio: 'inherit' });

console.error(`prepare: wrote packages/web/.ds-entry.mjs (${paths.length} sources) + .ds-compiled.css`);
