// flow-typed signature: 6bae02ffb61220afa463cfb8bb60e294
// flow-typed version: <<STUB>>/diff2html_v2.4.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diff2html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'diff2html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diff2html/dist/diff2html-ui' {
  declare module.exports: any;
}

declare module 'diff2html/dist/diff2html-ui.min' {
  declare module.exports: any;
}

declare module 'diff2html/dist/diff2html' {
  declare module.exports: any;
}

declare module 'diff2html/dist/diff2html.min' {
  declare module.exports: any;
}

declare module 'diff2html/src/diff-parser' {
  declare module.exports: any;
}

declare module 'diff2html/src/diff2html' {
  declare module.exports: any;
}

declare module 'diff2html/src/file-list-printer' {
  declare module.exports: any;
}

declare module 'diff2html/src/hoganjs-utils' {
  declare module.exports: any;
}

declare module 'diff2html/src/html-printer' {
  declare module.exports: any;
}

declare module 'diff2html/src/line-by-line-printer' {
  declare module.exports: any;
}

declare module 'diff2html/src/printer-utils' {
  declare module.exports: any;
}

declare module 'diff2html/src/rematch' {
  declare module.exports: any;
}

declare module 'diff2html/src/side-by-side-printer' {
  declare module.exports: any;
}

declare module 'diff2html/src/templates/diff2html-templates' {
  declare module.exports: any;
}

declare module 'diff2html/src/ui/js/diff2html-ui' {
  declare module.exports: any;
}

declare module 'diff2html/src/ui/js/highlight.js-internals' {
  declare module.exports: any;
}

declare module 'diff2html/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diff2html/dist/diff2html-ui.js' {
  declare module.exports: $Exports<'diff2html/dist/diff2html-ui'>;
}
declare module 'diff2html/dist/diff2html-ui.min.js' {
  declare module.exports: $Exports<'diff2html/dist/diff2html-ui.min'>;
}
declare module 'diff2html/dist/diff2html.js' {
  declare module.exports: $Exports<'diff2html/dist/diff2html'>;
}
declare module 'diff2html/dist/diff2html.min.js' {
  declare module.exports: $Exports<'diff2html/dist/diff2html.min'>;
}
declare module 'diff2html/src/diff-parser.js' {
  declare module.exports: $Exports<'diff2html/src/diff-parser'>;
}
declare module 'diff2html/src/diff2html.js' {
  declare module.exports: $Exports<'diff2html/src/diff2html'>;
}
declare module 'diff2html/src/file-list-printer.js' {
  declare module.exports: $Exports<'diff2html/src/file-list-printer'>;
}
declare module 'diff2html/src/hoganjs-utils.js' {
  declare module.exports: $Exports<'diff2html/src/hoganjs-utils'>;
}
declare module 'diff2html/src/html-printer.js' {
  declare module.exports: $Exports<'diff2html/src/html-printer'>;
}
declare module 'diff2html/src/line-by-line-printer.js' {
  declare module.exports: $Exports<'diff2html/src/line-by-line-printer'>;
}
declare module 'diff2html/src/printer-utils.js' {
  declare module.exports: $Exports<'diff2html/src/printer-utils'>;
}
declare module 'diff2html/src/rematch.js' {
  declare module.exports: $Exports<'diff2html/src/rematch'>;
}
declare module 'diff2html/src/side-by-side-printer.js' {
  declare module.exports: $Exports<'diff2html/src/side-by-side-printer'>;
}
declare module 'diff2html/src/templates/diff2html-templates.js' {
  declare module.exports: $Exports<'diff2html/src/templates/diff2html-templates'>;
}
declare module 'diff2html/src/ui/js/diff2html-ui.js' {
  declare module.exports: $Exports<'diff2html/src/ui/js/diff2html-ui'>;
}
declare module 'diff2html/src/ui/js/highlight.js-internals.js' {
  declare module.exports: $Exports<'diff2html/src/ui/js/highlight.js-internals'>;
}
declare module 'diff2html/src/utils.js' {
  declare module.exports: $Exports<'diff2html/src/utils'>;
}
