import { readFileSync } from 'node:fs';
import path from 'node:path';
import { RenderedAstEnvelopeSchema } from '@crowi/api-contract';
import type { PluginLogger } from '@crowi/plugin-api';
import { createPipelineEsmDepsLoader, runPipeline } from './pipeline';
import { RendererRegistryImpl } from './registry';
import { sanitizeAst } from './sanitize-ast';
import { serializeMdast } from './serialize';
import { RENDERER_PIPELINE_VERSION } from './version';

/**
 * RFC-0023 / parent spec §13 (Phase 3) — the shared golden fixture
 * corpus driver, the api-side (producer) consumer of
 * `__fixtures__/golden-corpus/*.json`.
 *
 * Each corpus case pins one or both directions of the shipped
 * behaviour:
 *
 *   - `markdown` → `expectedAst`: the stored bare-Root shape
 *     (`runPipeline` with an EMPTY registry + `mode: 'save'` — the
 *     pipeline.test.ts `runCore` pattern, Mongo-independent; no
 *     dispatch runs, so plugin-generated byte strings never enter the
 *     corpus — `packages/e2e/tests/renderer-plugins.spec.ts` owns
 *     those) followed by `serializeMdast`.
 *   - (`storedAst` | `expectedAst`) → `expectedEnvelope`: the
 *     `X-Crowi-Ast-Version: 1` projection via `sanitizeAst`. Synthetic
 *     `storedAst` inputs cover the sidecar projections dispatch would
 *     normally produce (`crowiMath` / `crowiDiagram` / `crowiLinkCard`
 *     / `crowiPlaceholder`); `crowiCode` alone comes from real shiki
 *     output (a core transform, so it DOES run here).
 *
 * The CrowiKit XCTest consumer (listed in every file's `consumers`)
 * asserts the mirror image: its Swift sanitize-walker over the stored
 * shapes and its strict decoder over the envelopes. It is wired up in
 * Phase 4 — `apps/apple` lives on the `feature-ios-app/impl` branch,
 * not in this worktree.
 *
 * Shiki color normalization (documented in `code.json`'s
 * `normalization` field, mirrored by the Swift driver): token style
 * `color` / `bgColor` values are replaced with `"<color>"` on BOTH
 * sides before comparison — colors are shiki/theme-version-dependent
 * styling; token line structure, `content` boundaries and `fontStyle`
 * are the pinned contract. The corpus itself must already be fully
 * normalized (asserted below), so real theme colors can never be
 * pinned by accident.
 */

const silentLogger: PluginLogger = {
  debug: () => undefined,
  info: () => undefined,
  warn: () => undefined,
  error: () => undefined,
};

const loadDeps = createPipelineEsmDepsLoader();
const runCore = async (body: string) => {
  const reg = new RendererRegistryImpl();
  return runPipeline(body, reg, { mode: 'save', log: silentLogger, actor: { kind: 'system' } }, loadDeps);
};

// ---------------------------------------------------------------------------
// Corpus loading.
// ---------------------------------------------------------------------------

interface GoldenCase {
  name: string;
  why: string;
  markdown?: string;
  expectedAst?: unknown;
  storedAst?: unknown;
  expectedEnvelope?: unknown;
}

interface GoldenCorpusFile {
  rule: string;
  why: string;
  consumers: string[];
  consumerContract: string;
  normalization: string;
  exclusions: string;
  cases: GoldenCase[];
}

const CORPUS_DIR = path.join(__dirname, '__fixtures__', 'golden-corpus');
const CORPUS_FILES = [
  'core-blocks.json',
  'inline.json',
  'code.json',
  'image-attrs.json',
  'gfm-references.json',
  'typed-nodes.json',
  'frontmatter.json',
] as const;

const corpus = CORPUS_FILES.map((file) => [file, JSON.parse(readFileSync(path.join(CORPUS_DIR, file), 'utf8')) as GoldenCorpusFile] as const);

/**
 * Parent-spec §13 "include" list → the case names that carry each
 * concept. A mechanical guard so a corpus edit cannot silently drop an
 * AC-mandated concept (e.g. the single-newline `break` case).
 */
const REQUIRED_CASES: Record<(typeof CORPUS_FILES)[number], string[]> = {
  'core-blocks.json': ['heading-anchor-basic', 'heading-anchor-duplicate', 'heading-anchor-cjk', 'gfm-table-align', 'task-list', 'ordered-list-start'],
  'inline.json': [
    'wikilink-absolute',
    'wikilink-display',
    'wikilink-broken',
    'mention',
    'single-newline-break',
    'emoji',
    'link-title',
    'image-inline-alt-title',
  ],
  'code.json': ['shiki-tokens', 'shiki-fontstyle', 'code-unknown-lang', 'code-no-lang', 'code-meta'],
  'image-attrs.json': [
    'figure-width-percent',
    'attr-boundary-percent-valid',
    'attr-boundary-px-valid',
    'attr-boundary-percent-invalid',
    'attr-boundary-px-invalid',
    'attr-out-of-range-percent',
    'attr-out-of-range-px',
    'attr-non-numeric',
    'attr-unit-less',
  ],
  'gfm-references.json': [
    'footnote',
    'link-reference-full',
    'image-reference',
    'link-reference-missing-reference-type',
    'link-reference-missing-identifier',
    'definition-missing-url',
    'definition-missing-identifier',
    'footnote-reference-missing-identifier',
    'footnote-definition-missing-identifier',
    'image-reference-missing-identifier',
    'image-reference-missing-reference-type',
  ],
  'typed-nodes.json': ['math-display-projection', 'math-inline-projection', 'diagram-mermaid-svg-projection', 'link-card-hoist', 'placeholder-projection'],
  'frontmatter.json': ['frontmatter-basic', 'frontmatter-mid-document-thematic-break-unaffected'],
};

// ---------------------------------------------------------------------------
// Shiki color normalization (see the module doc comment).
// ---------------------------------------------------------------------------

const COLOR_PLACEHOLDER = '<color>';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** A shiki token as the wire carries it: `content` + per-theme `light` / `dark` style objects. */
function isShikiToken(value: Record<string, unknown>): boolean {
  return typeof value.content === 'string' && isRecord(value.light) && isRecord(value.dark);
}

function normalizeStyle(style: unknown): unknown {
  if (!isRecord(style)) return style;
  const out: Record<string, unknown> = { ...style };
  if (typeof out.color === 'string') out.color = COLOR_PLACEHOLDER;
  if (typeof out.bgColor === 'string') out.bgColor = COLOR_PLACEHOLDER;
  return out;
}

function normalizeShikiColors(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeShikiColors);
  if (!isRecord(value)) return value;
  if (isShikiToken(value)) {
    return { ...value, light: normalizeStyle(value.light), dark: normalizeStyle(value.dark) };
  }
  const out: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value)) out[key] = normalizeShikiColors(entry);
  return out;
}

// ---------------------------------------------------------------------------
// Self-description — the corpus is a two-consumer contract and must say
// so itself (rule / why / consumers / normalization / exclusions).
// ---------------------------------------------------------------------------

describe('golden corpus self-description', () => {
  for (const [file, doc] of corpus) {
    describe(file, () => {
      it('describes its rule, rationale and normalization', () => {
        expect(doc.rule.length).toBeGreaterThan(0);
        expect(doc.why.length).toBeGreaterThan(0);
        expect(doc.normalization.length).toBeGreaterThan(0);
      });

      it('lists both consumers (this driver + the CrowiKit XCTest mirror)', () => {
        expect(doc.consumers).toContain('packages/api/src/renderer/golden-corpus.test.ts');
        expect(doc.consumers.some((c) => c.startsWith('apps/apple/CrowiKit/Tests/'))).toBe(true);
        expect(doc.consumerContract.length).toBeGreaterThan(0);
      });

      it('records why dispatch-generated byte strings are excluded', () => {
        expect(doc.exclusions).toContain('renderer-plugins.spec.ts');
      });

      it('contains every AC-mandated case', () => {
        const names = doc.cases.map((c) => c.name);
        for (const required of REQUIRED_CASES[file]) {
          expect(names).toContain(required);
        }
        // Case names double as test ids — they must be unique.
        expect(new Set(names).size).toBe(names.length);
      });

      it('every case is self-describing and pins at least one direction', () => {
        for (const c of doc.cases) {
          expect(c.name.length).toBeGreaterThan(0);
          expect(c.why.length).toBeGreaterThan(0);
          const hasSource = c.markdown !== undefined || c.storedAst !== undefined;
          const hasExpectation = c.expectedAst !== undefined || c.expectedEnvelope !== undefined;
          expect(hasSource).toBe(true);
          expect(hasExpectation).toBe(true);
          // A synthetic case has nothing to produce the stored shape from,
          // so it must pin the projection.
          if (c.markdown === undefined) expect(c.expectedEnvelope).toBeDefined();
        }
      });
    });
  }
});

// feature-renderer-frontmatter AC-10 — pinned so an accidental future
// bump/no-bump alongside an unrelated change is caught immediately (same
// convention as `util/page-response.test.ts`'s own pinned assertion).
// The complementary half of AC-10 — a STALE stored AST (older
// `rendererVersion`) recomputes per read against the running pipeline,
// with no write-back to the stored document — is pre-existing generic
// freshness-comparison infra (`util/page-response.ts`), already covered
// by `page-response.test.ts`; nothing new to re-test here.
describe('renderer version (feature-renderer-frontmatter AC-10)', () => {
  it('RENDERER_PIPELINE_VERSION is 1.1.0 (new bundled frontmatter transform — minor bump)', () => {
    expect(RENDERER_PIPELINE_VERSION).toBe('1.1.0');
  });
});

// ---------------------------------------------------------------------------
// The cases.
// ---------------------------------------------------------------------------

describe('golden corpus', () => {
  for (const [file, doc] of corpus) {
    describe(file, () => {
      for (const c of doc.cases) {
        it(c.name, async () => {
          // The stored-AST shape: produced by the real pipeline for
          // markdown cases, taken verbatim for synthetic ones.
          let stored: unknown;
          if (c.markdown !== undefined) {
            const { tree } = await runCore(c.markdown);
            stored = serializeMdast(tree);
            if (c.expectedAst !== undefined) {
              expect(stored).toEqual(c.expectedAst);
            }
          } else {
            stored = c.storedAst;
          }

          if (c.expectedEnvelope === undefined) return;

          // The corpus itself must be fully normalized — a real theme
          // color pinned by accident would make normalize() a no-op
          // mismatch here before it ever flakes on a shiki upgrade.
          expect(normalizeShikiColors(c.expectedEnvelope)).toEqual(c.expectedEnvelope);

          // The expected envelope must satisfy the strict wire schema
          // (placeholder colors included) — it is what the iOS strict
          // decoder consumes.
          expect(() => RenderedAstEnvelopeSchema.parse(c.expectedEnvelope)).not.toThrow();

          const actual = sanitizeAst(stored);
          // Presence-only verification of theme colors: the strict
          // schema requires `color` on every token style, but pins no
          // value — the placeholder comparison below is what the
          // corpus actually fixes.
          expect(() => RenderedAstEnvelopeSchema.parse(actual)).not.toThrow();
          expect(normalizeShikiColors(actual)).toEqual(c.expectedEnvelope);
        });
      }
    });
  }
});
