import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

// Minimal Vitest setup, scoped to component-level unit tests. We do
// NOT load Next.js / Tailwind here — the only consumer right now is
// the MarkdownEditor smoke tests (RFC-0003 Phase 1). Wider coverage
// (server actions, route handlers, full app render) is intentionally
// deferred until there is a concrete need.
//
// Path alias resolution mirrors tsconfig's `@/*` → `src/*` so test
// files can use the same imports as production code.
export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: false,
    include: ['src/**/*.test.{ts,tsx}'],
    // jest-dom matchers + global cleanup + jsdom matchMedia/navigation stubs.
    setupFiles: ['./vitest.setup.ts'],
    // Deterministic clock-independent assertions: pin to UTC so date / time
    // formatters can't render differently on a non-UTC dev/CI host.
    env: {
      TZ: 'UTC',
    },
    // Reset mock call history (clearMocks) and restore spied-on originals
    // (restoreMocks) between tests, and undo vi.stubGlobal/stubEnv
    // (unstubGlobals) so no test leaks state into the next one.
    clearMocks: true,
    restoreMocks: true,
    unstubGlobals: true,
    // Paraglide compiled output is generated by `pnpm paraglide:compile`
    // (already run via the `pretest` hook below). Aliasing the
    // `@paraglide` virtual into the compiled dir keeps the test
    // resolver happy without depending on Next's tsconfig paths plugin.
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@paraglide': path.resolve(__dirname, './paraglide'),
    },
  },
});
