import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

// Minimal Vitest setup, scoped to component-level unit tests. We do
// NOT load Next.js / Tailwind here — the only consumer right now is
// the MarkdownEditor smoke tests (RFC-0003 Phase 1). Wider coverage
// (server actions, route handlers, full app render) is intentionally
// deferred until there is a concrete need.
//
// Path alias resolution mirrors tsconfig's `@/*` → `src/*` so test
// files can use the same imports as production code.
export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: false,
    include: ['src/**/*.test.{ts,tsx}'],
    // Paraglide compiled output is generated by `pnpm paraglide:compile`
    // (already run via the `pretest` hook below). Aliasing the
    // `@paraglide` virtual into the compiled dir keeps the test
    // resolver happy without depending on Next's tsconfig paths plugin.
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@paraglide': path.resolve(__dirname, './paraglide'),
    },
  },
});
