// swift-tools-version: 5.10

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Crowi",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Crowi",
            targets: ["CrowiApp"],
            bundleIdentifier: "wiki.crowi.ios",
            teamIdentifier: "NM88B932JW",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ],
            additionalInfoPlistContentFilePath: "Support/AdditionalInfo.plist"
        )
    ],
    dependencies: [
        .package(path: "../CrowiKit")
    ],
    targets: [
        .executableTarget(
            name: "CrowiApp",
            dependencies: [
                .product(name: "CrowiKit", package: "CrowiKit")
            ],
            resources: [
                .process("Resources")
            ]
        )
    ]
)