module.exports = (crowi, app) => ({
  Version: require('./version')(crowi, app),
  Admin: require('./admin')(crowi, app),
  Attachment: require('./attachment')(crowi, app),
  Backlink: require('./backlink')(crowi, app),
  Bookmark: require('./bookmark')(crowi, app),
  Comment: require('./comment')(crowi, app),
  Installer: require('./installer')(crowi, app),
  Login: require('./login')(crowi, app),
  Logout: require('./logout')(crowi, app),
  Me: require('./me')(crowi, app),
  Notification: require('./notification')(crowi, app),
  Page: require('./page')(crowi, app),
  Revision: require('./revision')(crowi, app),
  Search: require('./search')(crowi, app),
  Share: require('./share')(crowi, app),
  ShareAccess: require('./shareAccess')(crowi, app),
  Slack: require('./slack')(crowi, app),
  User: require('./user')(crowi, app),
})
