// Per-worktree single-origin dev proxy (feature-dev-portal-worktree §4 — the
// core of this feature): same-origin access to web + api + the collab /
// presence / notifications WebSocket namespaces, so realtime editing works
// from an iPhone over tailscale (Next.js `rewrites()` is HTTP-only and can't
// forward the WS `upgrade`).
//
// Caddy is the first choice — the repo already ships a prod `Caddyfile` with
// this exact routing table (path → api vs web, WS bare + `/*` both matched).
// `generateCaddyfile()` below is that same routing table, parameterized for a
// worktree's anchor and rendered as a throwaway per-worktree config file
// (kept outside the repo, like the port registry, so `pnpm dev` never dirties
// the working tree). When the `caddy` binary isn't installed, `pnpm dev` falls
// back to `startNodeProxyFallback()`, a zero-dep `http`/`net` proxy that
// implements the same three routing gotchas by hand:
//   (a) match on the path with any `?query` stripped first,
//   (b) forward the WebSocket upgrade with a real bidirectional pipe, closing
//       the other side the moment either end closes or errors,
//   (c) forward the original `Host` header upstream (Next's `allowedDevOrigins`
//       gate and some absolute-URL building read it).

import { execFileSync, spawn } from 'node:child_process'
import fs from 'node:fs'
import http from 'node:http'
import net from 'node:net'
import os from 'node:os'
import path from 'node:path'

export const DEFAULT_CADDY_CONFIG_DIR = path.join(os.homedir(), '.crowi-dev-caddy')

// Paths routed to the api (HTTP). `/.well-known/oauth-authorization-server` is
// included per the spec's open-question default: cheap to add, and it lets
// `@crowi/cli`'s OAuth discovery work against the proxy origin.
export const API_HTTP_PATHS = ['/api', '/files', '/.well-known/oauth-authorization-server']
// Realtime namespaces routed to the api (WS). Each must be matched BOTH bare
// and with a `/*` suffix — Caddy's `path /collab/*` does NOT match a bare
// `/collab`, and the browser dials the bare namespace (Hocuspocus / presence /
// notifications carry document/page id in the protocol, not the path).
export const WS_NAMESPACES = ['collab', 'presence', 'notifications']

/**
 * Render a per-worktree Caddyfile: same routing table as the repo's prod
 * `Caddyfile`, targets pointed at `localhost:<apiPort>` / `localhost:<webPort>`,
 * listening on `<listenHost>:<proxyPort>`. Bound to loopback only by default —
 * `tailscale serve` reaches it via its own loopback target, so there's no need
 * to expose the raw proxy port on every interface.
 * @param {{ apiPort: number, webPort: number, proxyPort: number, listenHost?: string }} params
 * @returns {string}
 */
export function generateCaddyfile({ apiPort, webPort, proxyPort, listenHost = '127.0.0.1' }) {
  const apiPathList = API_HTTP_PATHS.flatMap((p) => [p, `${p}/*`]).join(' ')
  const wsPathList = WS_NAMESPACES.flatMap((ns) => [`/${ns}`, `/${ns}/*`]).join(' ')
  return `# Generated by scripts/dev-caddy.mjs — DO NOT EDIT BY HAND.
# Regenerated on every \`pnpm dev\`. Per-worktree same-origin dev proxy, mirrors
# the routing table in the repo-root Caddyfile (prod \`app\` profile).
${listenHost}:${proxyPort} {
	# HTTP API + attachments (+ OAuth discovery) → api
	@api path ${apiPathList}
	reverse_proxy @api localhost:${apiPort}

	# Realtime WebSocket namespaces → api. Caddy forwards the WS Upgrade
	# automatically. Bare namespace AND /* sub-path both matched (see
	# WS_NAMESPACES doc comment above).
	@ws path ${wsPathList}
	reverse_proxy @ws localhost:${apiPort}

	# Everything else → web (Next.js, incl. Turbopack HMR WS)
	reverse_proxy localhost:${webPort}
}
`
}

/**
 * Where the generated Caddyfile for a given worktree key lives. Outside the
 * repo (`~/.crowi-dev-caddy/`), same rationale as the port registry: never
 * dirty the working tree, and it must survive independently of any one
 * worktree's lifecycle for inspection/debugging.
 * @param {string} key
 * @param {string} [dir]
 */
export function caddyConfigPathFor(key, dir = DEFAULT_CADDY_CONFIG_DIR) {
  return path.join(dir, `${key}.Caddyfile`)
}

/**
 * Write the generated Caddyfile for `key`, creating the config dir if needed.
 * @param {string} key
 * @param {string} content
 * @param {string} [dir]
 * @returns {string} the path written
 */
export function writeCaddyConfig(key, content, dir = DEFAULT_CADDY_CONFIG_DIR) {
  fs.mkdirSync(dir, { recursive: true })
  const configPath = caddyConfigPathFor(key, dir)
  fs.writeFileSync(configPath, content)
  return configPath
}

/** Whether the `caddy` binary is on PATH and runnable. */
export function isCaddyAvailable() {
  try {
    execFileSync('caddy', ['version'], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

/**
 * Spawn `caddy run` against a generated config. Caller owns the returned
 * child (kill with SIGTERM for a graceful shutdown; caddy handles it).
 * @param {string} configPath
 * @returns {import('node:child_process').ChildProcess}
 */
export function startCaddyProcess(configPath) {
  return spawn('caddy', ['run', '--config', configPath, '--adapter', 'caddyfile'], {
    stdio: ['ignore', 'pipe', 'pipe'],
  })
}

// ── zero-dep node proxy fallback (no Caddy installed) ──

/**
 * Decide whether a request path should go to the api or the web dev server.
 * Pure — strips the query string before comparing, matches bare namespace AND
 * `/*` sub-path form. Exported so the routing table itself is unit-testable
 * without spinning up real sockets.
 * @param {string} rawUrl `req.url` (may include a query string)
 * @returns {'api' | 'web'}
 */
export function pickProxyTarget(rawUrl) {
  const pathname = rawUrl.split('?')[0]
  const isApiHttp = API_HTTP_PATHS.some((p) => pathname === p || pathname.startsWith(`${p}/`))
  const isWs = WS_NAMESPACES.some((ns) => pathname === `/${ns}` || pathname.startsWith(`/${ns}/`))
  return isApiHttp || isWs ? 'api' : 'web'
}

/**
 * Zero-dep fallback proxy for hosts without `caddy` installed. Implements the
 * same routing table as `generateCaddyfile()` by hand over `node:http` (plain
 * requests) and `node:net` (WebSocket upgrades — proxied at the raw socket
 * level so the handshake/frames pass through untouched).
 * @param {{ apiPort: number, webPort: number, proxyPort: number, listenHost?: string }} params
 * @returns {import('node:http').Server}
 */
export function startNodeProxyFallback({ apiPort, webPort, proxyPort, listenHost = '127.0.0.1' }) {
  const portFor = (rawUrl) => (pickProxyTarget(rawUrl) === 'api' ? apiPort : webPort)

  const server = http.createServer((req, res) => {
    const targetPort = portFor(req.url)
    const proxyReq = http.request(
      { host: '127.0.0.1', port: targetPort, method: req.method, path: req.url, headers: req.headers },
      (proxyRes) => {
        res.writeHead(proxyRes.statusCode ?? 502, proxyRes.headers)
        proxyRes.pipe(res)
      },
    )
    proxyReq.on('error', () => {
      if (!res.headersSent) res.writeHead(502)
      res.end('dev-caddy fallback: bad gateway')
    })
    req.pipe(proxyReq)
  })

  server.on('upgrade', (req, clientSocket, head) => {
    const targetPort = portFor(req.url)
    const upstream = net.connect(targetPort, '127.0.0.1', () => {
      const requestLine = `${req.method} ${req.url} HTTP/1.1\r\n`
      const headerLines = Object.entries(req.headers)
        .map(([k, v]) => (Array.isArray(v) ? v.map((vv) => `${k}: ${vv}`).join('\r\n') : `${k}: ${v}`))
        .join('\r\n')
      upstream.write(`${requestLine}${headerLines}\r\n\r\n`)
      if (head && head.length) upstream.write(head)
      // Bidirectional pipe; either side closing/erroring tears down both —
      // a half-open WS after the api or the browser goes away is a classic
      // hand-rolled-proxy leak.
      upstream.pipe(clientSocket)
      clientSocket.pipe(upstream)
    })
    const teardown = () => {
      upstream.destroy()
      clientSocket.destroy()
    }
    upstream.on('error', teardown)
    clientSocket.on('error', teardown)
    upstream.on('close', () => clientSocket.destroy())
    clientSocket.on('close', () => upstream.destroy())
  })

  server.listen(proxyPort, listenHost)
  return server
}
