#!/usr/bin/env -S node --experimental-strip-types
/**
 * RFC-0006 Phase 6 — `openapi-typescript` runner.
 *
 * Reads `packages/api-contract/openapi.json` (regenerated upstream by
 * `scripts/generate-openapi.ts`) and emits a TypeScript module at
 * `packages/api-contract/src/generated/openapi.ts`. The generated file
 * is committed to the repo and gated by `git diff --exit-code` in CI,
 * mirroring how `openapi.json` / `openapi.yaml` are already tracked.
 *
 * Why a committed artefact instead of a build-time step:
 *   - External / cross-language consumers (e.g. CLI tooling, future
 *     non-TS SDKs) can read the generated types directly from the
 *     published package without running our build.
 *   - The CI gate catches contract drift: any change to a Zod schema
 *     or `createRoute(...)` definition must regenerate this file in
 *     the same commit, making schema churn visible in code review.
 *
 * Idempotency: we always rewrite the file. Re-running this script
 * after no source change must leave the working tree clean — that is
 * the property CI asserts.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, '..');
const inputPath = join(packageRoot, 'openapi.json');
const outputPath = join(packageRoot, 'src', 'generated', 'openapi.ts');

const HEADER = `/**
 * AUTO-GENERATED by \`pnpm --filter @crowi/api-contract generate-openapi-types\`.
 *
 * Source: \`packages/api-contract/openapi.json\` (RFC-0006 Phase 6 onwards).
 * Do NOT edit by hand — re-run the generator instead. CI verifies this
 * file stays in sync via \`git diff --exit-code\` after a fresh generate.
 */

`;

async function main() {
  const ast = await openapiTS(new URL(`file://${inputPath}`));
  const body = astToString(ast);

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${HEADER}${body}`);
  console.log(`OpenAPI TypeScript types generated at: ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
